apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
  namespace: scaling
spec:
  containers:
      - name: stress
        image: progrium/stress
        args:
        - "--cpu"
        - "2"
        - "--timeout"
        - "60"
