apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit
  namespace: limit
spec:
  selector:
    matchLabels:
      app: limit
  template:
    metadata:
      labels:
        app: limit
    spec:
      containers:
        - name: limit
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
          volumeMounts:
           - mountPath: "/usr/share/nginx/html"
             name: mypv

      volumes:
        - name: mypv
          persistentVolumeClaim:
            claimName: mypvc
