apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: limit
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
