apiVersion: batch/v1
kind: CronJob
metadata:
  name: minute-backup
  namespace: nginx
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-container
              image: busybox:latest
              command:
                - /bin/sh
                - -c
                - date; echo "backup started" ;
          restartPolicy: OnFailure
