apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-pod
          image: nginx:latest
      resources:
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: myvolume

      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: localpv
