apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localpv
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
  volumeMode: Filesystem
