---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# Install Argo CD
# This is copied from official manifest https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# For brevity, only main resources are shown; you can copy full manifest into your file
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  namespace: argocd
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.9.5
          ports:
            - containerPort: 8080
