kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devops.himanshu.com
spec:
  group: himanshu.com
  names:
    kind: Devops
    plural: devops
    singular: devops
    shortNames: 
        - dvs
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                branch:
                  type: string
                buildTool:
                  type: string
              required:
                - name
                - branch
                - buildTool
      subresources:
        status: {}
